### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by briatte** [bdoms/tumblr_backup#6]
This issue causes the script to terminate. Apologies for not being able to understand the output enough to recommend a solution. It looks like a picture from the blog is causing trouble (Error 403); perhaps Tumblr is throttling the script?

    Downloading a photo. This may take a moment.
    Traceback (most recent call last):
        File "/Users/fr/Public/tumblr_backup-master/tumblr_backup.py", line 283, in <module>
                backup(account, use_csv, save_folder)
        File "/Users/fr/Public/tumblr_backup-master/tumblr_backup.py", line 257, in backup
                savePost(post, save_folder, header=header)
        File "/Users/fr/Public/tumblr_backup-master/tumblr_backup.py", line 101, in savePost
                image_response = urllib2.urlopen(image_url)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
                return _opener.open(url, data, timeout)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
                response = meth(req, response)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
                'http', request, response, code, msg, hdrs)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
                return self._call_chain(*args)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
                result = func(*args)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: Forbidden

Hope this helps!

**Comment by bdoms** [comment]
I checked this exact case again and Tumblr appears to have resolved this issue on their end.
